Team9_winxshop/Models/DonHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team9_winxshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ChiTietThanhToans = new HashSet<ChiTietThanhToan>();
        }
    
        public int MaDH { get; set; }
        public string Email { get; set; }
        public int MaTT { get; set; }
        public string DiaChiNguoiNhan { get; set; }
        public string SDT { get; set; }
        public int TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThanhToan> ChiTietThanhToans { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual TrangThaiDonHang TrangThaiDonHang { get; set; }
    }
}

Team9_winxshop/Controllers/DonHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Team9_winxshop.Models;

namespace Team9_winxshop.Controllers
{
    public class DonHangsController : Controller
    {
        private CT25Team19Entities db = new CT25Team19Entities();
        [Authorize(Roles = "Admin")]
        // GET: DonHangs
        public ActionResult Index()
        {
            var model = db.DonHangs.ToList();
            return View(model);
        }

        public ActionResult Search(string keyword)
        {
            var model = db.DonHangs.ToList();
            model = model.Where(p => p.MaDH.ToString().Contains(keyword)
                                || p.Email.ToLower().Contains(keyword.ToLower())).ToList();
            ViewBag.Keyword = keyword;
            return View("Index", model);
        }

        // GET: DonHangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // GET: DonHangs/Create
        public ActionResult Create()
        {
            ViewBag.MaTT = new SelectList(db.TrangThaiDonHangs, "MaTT", "TrangThai");
            return View();
        }

        // POST: DonHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDH,Email,MaTT,DiaChiNguoiNhan,SDT")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                db.DonHangs.Add(donHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaTT = new SelectList(db.TrangThaiDonHangs, "MaTT", "TrangThai", donHang.MaTT);
            return View(donHang);
        }

        // GET: DonHangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaTT = new SelectList(db.TrangThaiDonHangs, "MaTT", "TrangThai", donHang.MaTT);
            return View(donHang);
        }

        // POST: DonHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDH,Email,MaTT,DiaChiNguoiNhan,SDT,TongTien")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaTT = new SelectList(db.TrangThaiDonHangs, "MaTT", "TrangThai", donHang.MaTT);
            return View(donHang);
        }

        // GET: DonHangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // POST: DonHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DonHang donHang = db.DonHangs.Find(id);
            db.DonHangs.Remove(donHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Team9_winxshop/Views/DonHangs/Delete.cshtml
@model Team9_winxshop.Models.DonHang

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>DonHang</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DiaChiNguoiNhan)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DiaChiNguoiNhan)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SDT)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SDT)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TrangThaiDonHang.TrangThai)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TrangThaiDonHang.TrangThai)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Team9_winxshop/Views/DonHangs/Details.cshtml
@model Team9_winxshop.Models.DonHang

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>DonHang</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DiaChiNguoiNhan)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DiaChiNguoiNhan)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.SDT)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SDT)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TrangThaiDonHang.TrangThai)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TrangThaiDonHang.TrangThai)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.MaDH }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Team9_winxshop/Views/DonHangs/Edit.cshtml
@model Team9_winxshop.Models.DonHang

@{
    ViewBag.Title = "Edit";
}

<header class="header-section">
    <div class="header-top">
        <div class="container">
            <div class="ht-left">
                <div class="mail-service">
                    <i class=" fa fa-envelope"></i>
                    winxshop@gmail.com
                </div>
                <div class="phone-service">
                    <i class=" fa fa-phone"></i>
                    +65 11.188.888
                </div>
            </div>
            <div class="ht-right">
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="login-panel">Đăng xuất</a>
                    }
                }
                else
                {
                    <a href="@Url.Action("Login", "Account")" class="login-panel"><i class="fa fa-user"></i>Đăng nhập</a>
                }
            </div>
        </div>
    </div>
    <div class="container">
        <div class="inner-header">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="logo">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="@Url.Content("~/assets/img/logo.jpg")" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<h2>Cập nhật trạng thái đơn hàng</h2>


<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4 style="padding: 10px">Đơn hàng @Model.MaDH</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MaDH)

            <div class="form-group">
                <label class="control-label col-md-2">Email khách hàng</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Trạng thái</label>
                <div class="col-md-10">
                    @Html.DropDownList("MaTT", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaTT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Địa chỉ</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DiaChiNguoiNhan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiaChiNguoiNhan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Số điện thoại</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Tổng tiền</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TongTien, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TongTien, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" style="border-color: #e7ab3c;" /> |
                    @Html.ActionLink("Quay lại danh sách", "Index")
                </div>
            </div>
        </div>
    }
</body>

Team9_winxshop/Views/DonHangs/Index.cshtml
@model IEnumerable<Team9_winxshop.Models.DonHang>

@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>

<header class="header-section">
    <div class="header-top">
        <div class="container">
            <div class="ht-left">
                <div class="mail-service">
                    <i class=" fa fa-envelope"></i>
                    winxshop@gmail.com
                </div>
                <div class="phone-service">
                    <i class=" fa fa-phone"></i>
                    +65 11.188.888
                </div>
            </div>
            <div class="ht-right">
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="login-panel">Đăng xuất</a>
                    }
                }
                else
                {
                    <a href="@Url.Action("Login", "Account")" class="login-panel"><i class="fa fa-user"></i>Đăng nhập</a>
                }
            </div>
        </div>
    </div>
    <div class="container">
        <div class="inner-header">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="logo">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="@Url.Content("~/assets/img/logo.jpg")" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-7 col-md-7">
                    <form action="@Url.Action("Search", "DonHangs")" method="get">
                        <div class="advanced-search" style="width: 500px;">
                            <div class="input-group">
                                <input type="text" name="Keyword" placeholder="Nhập đơn hàng bạn muốn tìm kiếm">
                                <button type="submit" style="right: -200px;"><i class="ti-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</header>
<h2 style="padding: 8px; border-bottom: 1px solid #e7ab3c">Danh sách đơn hàng</h2>
<body>
    <h5 style="padding: 10px">Đơn hàng đang chờ xử lý</h5>
    <table class="table">
        <tr>
            <th>
                Mã đơn hàng
            </th>
            <th>
                Email khách hàng
            </th>
            <th>
                Địa chỉ
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Tổng tiền
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            if (item.TrangThaiDonHang.TrangThai == "Đang chờ xử lý")
            {
                <tr>
                    <td>
                        @item.MaDH
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.DiaChiNguoiNhan
                    </td>
                    <td>
                        @item.SDT
                    </td>
                    <td>
                        @item.TongTien.ToString("N0")@("đ")
                    </td>
                    <td>
                        <a href="@Url.Action("Search", "ChiTietDonHangs", new { keyword = item.MaDH })">
                            Xem chi tiết đơn hàng
                        </a> <br />
                        <a href="@Url.Action("Edit", new { id = item.MaDH })">
                            Cập nhật trạng thái đơn hàng
                        </a>
                    </td>
                </tr>
            }
        }

    </table>
    <h5 style="padding: 10px; border-top: 1px solid #e7ab3c">Đơn hàng đã xác nhận</h5>
    <table class="table">
        <tr>
            <th>
                Mã đơn hàng
            </th>
            <th>
                Email khách hàng
            </th>
            <th>
                Địa chỉ
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Tổng tiền
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            if (item.TrangThaiDonHang.TrangThai == "Đã xác nhận")
            {
                <tr>
                    <td>
                        @item.MaDH
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.DiaChiNguoiNhan
                    </td>
                    <td>
                        @item.SDT
                    </td>
                    <td>
                        @item.TongTien.ToString("N0")@("đ")
                    </td>
                    <td>
                        <a href="@Url.Action("Search", "ChiTietDonHangs", new { keyword = item.MaDH })">
                            Xem chi tiết đơn hàng
                        </a> <br />
                        <a href="@Url.Action("Edit", new { id = item.MaDH })">
                            Cập nhật trạng thái đơn hàng
                        </a>
                    </td>
                </tr>
            }
        }

    </table>
    <h5 style="padding: 10px; border-top: 1px solid #e7ab3c">Đơn hàng đã hoàn thành</h5>
    <table class="table">
        <tr>
            <th>
                Mã đơn hàng
            </th>
            <th>
                Email khách hàng
            </th>
            <th>
                Địa chỉ
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Tổng tiền
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            if (item.TrangThaiDonHang.TrangThai == "Hoàn thành")
            {
                <tr>
                    <td>
                        @item.MaDH
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.DiaChiNguoiNhan
                    </td>
                    <td>
                        @item.SDT
                    </td>
                    <td>
                        @item.TongTien.ToString("N0")@("đ")
                    </td>
                    <td>
                        <a href="@Url.Action("Search", "ChiTietDonHangs", new { keyword = item.MaDH })">
                            Xem chi tiết đơn hàng
                        </a> <br />
                        <a href="@Url.Action("Edit", new { id = item.MaDH })">
                            Cập nhật trạng thái đơn hàng
                        </a>
                    </td>
                </tr>
            }
        }

    </table>
    <h5 style="padding: 10px; border-top: 1px solid #e7ab3c">Đơn hàng đã hủy</h5>
    <table class="table">
        <tr>
            <th>
                Mã đơn hàng
            </th>
            <th>
                Email khách hàng
            </th>
            <th>
                Địa chỉ
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Tổng tiền
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            if (item.TrangThaiDonHang.TrangThai == "Hủy")
            {
                <tr>
                    <td>
                        @item.MaDH
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.DiaChiNguoiNhan
                    </td>
                    <td>
                        @item.SDT
                    </td>
                    <td>
                        @item.TongTien.ToString("N0")@("đ")
                    </td>
                    <td>
                        <a href="@Url.Action("Search", "ChiTietDonHangs", new { keyword = item.MaDH })">
                            Xem chi tiết đơn hàng
                        </a> <br />
                        <a href="@Url.Action("Edit", new { id = item.MaDH })">
                            Cập nhật trạng thái đơn hàng
                        </a>
                    </td>
                </tr>
            }
        }

    </table>
</body>