Team9_winxshop/Models/GioHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team9_winxshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GioHang()
        {
            this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();
        }
    
        public int MaGH { get; set; }
        public string Email { get; set; }
        public int TongTien { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}

Team9_winxshop/Controllers/GioHangsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Team9_winxshop.Models;

namespace Team9_winxshop.Controllers
{
    [Authorize]
    public class GioHangsController : Controller
    {
        private CT25Team19Entities db = new CT25Team19Entities();
        private List<ChiTietGioHang> ShoppingCart = null;

        public GioHangsController()
        {
            var session = System.Web.HttpContext.Current.Session;
            if(session["ShoppingCart"] != null)
            {
                ShoppingCart = session["ShoppingCart"] as List<ChiTietGioHang>;
            }
            else
            {
                ShoppingCart = new List<ChiTietGioHang>();
                session["ShoppingCart"] = ShoppingCart;
            }
        }

        // GET: GioHangs
        public ActionResult Index()
        {
            var hashtable = new Hashtable();
            foreach(var billdetail in ShoppingCart)
            {
                if (hashtable[billdetail.SanPham.MaSP] != null)
                {
                    (hashtable[billdetail.SanPham.MaSP] as ChiTietGioHang).SoLuong += billdetail.SoLuong;
                }
                else
                {
                    hashtable[billdetail.SanPham.MaSP] = billdetail;
                }
            }

            ShoppingCart.Clear();
            foreach(ChiTietGioHang ctgh in hashtable.Values)
            {
                ShoppingCart.Add(ctgh);
            }

            return View(ShoppingCart);
        }

        [AllowAnonymous]
        // GET: GioHangs/Create
        [HttpPost]
        public ActionResult Create(string productId, int quantity)
        {
            var product = db.SanPhams.Find(productId);
            ShoppingCart.Add(new ChiTietGioHang
            {
                SanPham = product,
                SoLuong = quantity,
            });
            return RedirectToAction("Index");
        }

        // GET: GioHangs/Edit/5
        public ActionResult UpdateCart(int[] quantity)
        {
            for(int i = 0; i < ShoppingCart.Count; i++)
            {
                ShoppingCart[i].SoLuong = quantity[i];
            }
            return RedirectToAction("Index");
        }

        public ActionResult CheckOut()
        {
            return View(ShoppingCart);
        }

        public ActionResult Success(FormCollection frc)
        {
            DonHang donhang = new DonHang
            {
                Email = frc["khEmail"],
                MaTT = 1,
                DiaChiNguoiNhan = frc["khDiachi"],
                SDT = frc["khSodt"],
                TongTien = Int32.Parse(frc["TTien"]),
            };
            db.DonHangs.Add(donhang);
            db.SaveChanges();

            foreach (var billdetail in ShoppingCart)
            {
                ChiTietDonHang ctdh = new ChiTietDonHang()
                {
                    MaDH = donhang.MaDH,
                    MaSP = billdetail.SanPham.MaSP,
                    SoLuong = billdetail.SoLuong,
                };
                db.ChiTietDonHangs.Add(ctdh);
                db.SaveChanges();
            }
            ShoppingCart.Clear();
            return View("Success");
        }

        public ActionResult Delete(string productId)
        {
            foreach (var billdetail in ShoppingCart)
            {
                if (billdetail.MaSP == productId)
                {
                    ShoppingCart.Remove(billdetail);
                    break;
                }
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Team9_winxshop/Views/GioHangs/CheckOut.cshtml
@model IEnumerable<Team9_winxshop.Models.ChiTietGioHang>
@using Team9_winxshop.Models

@{
    ViewBag.Title = "CheckOut";
}
<!-- Header Section Begin -->
<header class="header-section">
    <div class="header-top">
        <div class="container">
            <div class="ht-left">
                <div class="mail-service">
                    <i class=" fa fa-envelope"></i>
                    winxshop@gmail.com
                </div>
                <div class="phone-service">
                    <i class=" fa fa-phone"></i>
                    +65 11.188.888
                </div>
            </div>
            <div class="ht-right">
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="login-panel">Đăng xuất</a>
                    }
                }
                else
                {
                    <a href="@Url.Action("Login", "Account")" class="login-panel"><i class="fa fa-user"></i>Đăng nhập</a>
                }
            </div>
        </div>
    </div>
    <div class="container">
        <div class="inner-header">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="logo">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="@Url.Content("~/assets/img/logo.jpg")" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-7 col-md-7">
                    <form action="@Url.Action("Search", "SanPhams")" method="get">
                        <div class="advanced-search" style="width: 500px;">
                            <div class="input-group">
                                <input type="text" maxlength="30" name="Keyword" placeholder="Nhập sản phẩm bạn muốn tìm kiếm">
                                <button type="submit" style="right: -200px;"><i class="ti-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-3 text-right col-md-3">
                    <ul class="nav-right">
                        <li class="cart-icon">
                            <a href="@Url.Action("Index", "GioHangs")">
                                <i class="icon_bag_alt"></i>
                                <span>@((Session["ShoppingCart"] as List<ChiTietGioHang>)?.Count.ToString()) </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="nav-item">
        <div class="container">
            <div class="nav-depart">
                <div class="depart-btn">
                    <i class="ti-menu"></i>
                    <span>All departments</span>
                    <form action="@Url.Action("Search", "SanPhams")" method="get">
                        <ul class="depart-hover">
                            <li><button type="submit" name="Keyword" value="Nữ" style="display: block; font-size: 16px; color: #e7ab3c; padding-left: 40px; padding-top: 16px; padding-right: 30px; border: none; background-color: #fff">Women</button></li>
                            <li><button type="submit" name="Keyword" value="Nam" style="display: block; font-size: 16px; color: #e7ab3c; padding-left: 40px; padding-top: 16px; padding-right: 30px; border: none; background-color: #fff">Men</button></li>
                        </ul>
                    </form>
                </div>
            </div>
            <nav class="nav-menu mobile-menu">
                <ul>
                    <li class="active"><a href="@Url.Action("Index", "Home")">Trang chủ</a></li>
                    <li><a href="@Url.Action("Index2", "SanPhams")">Sản phẩm</a></li>
                    <li><a href="@Url.Action("About", "Home")">Về Winxshop</a></li>
                    <li><a href="@Url.Action("Contact", "Home")">Liên hệ</a></li>
                </ul>
            </nav>
            <div id="mobile-menu-wrap"></div>
        </div>
    </div>
</header>
<div class="breadcrumb-text product-more">
    <a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Trang chủ</a>
    <a href="@Url.Action("Index", "GioHangs")">Giỏ hàng</a>
    <span>Thanh toán</span>
</div>

<section class="checkout-section spad">
    <div class="container">
        <form action="@Url.Action("Success", "GioHangs")" class="checkout-form" method="post">
            <div class="row">
                <div class="col-lg-6">
                    <h4>Thông tin giao hàng</h4>
                    <div class="row">
                        <div class="col-lg-12">
                            <label for="cusEmail">Email<span style="color: red">*</span></label>
                            <input type="email" name="khEmail" required>
                        </div>
                        <div class="col-lg-12">
                            <label for="cusDiachi">Địa chỉ<span style="color: red">*</span></label>
                            <input type="text" name="khDiachi" required>
                        </div>
                        <div class="col-lg-12">
                            <label for="cusPhone">Số điện thoại<span style="color: red">*</span></label>
                            <input type="text" name="khSodt" required>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="place-order">
                        <a href="@Url.Action("Index", "GioHangs")"><h4>Giỏ hàng của của bạn</h4></a>
                        <div class="order-total">
                            <ul class="order-table">
                                <li>Sản phẩm <span>Tổng tiền</span></li>
                                @foreach (var product in Model)
                                {
                                    <li class="fw-normal">@product.SanPham.TenSP x @product.SoLuong<span>@((product.SanPham.DonGia * product.SoLuong).ToString("N0"))đ</span></li>
                                }
                                @{
                                    List<ChiTietGioHang> temp = (List<ChiTietGioHang>)Session["ShoppingCart"];
                                    var total = String.Format("{0:N0}", temp.Sum(x => x.SoLuong * x.SanPham.DonGia));
                                    var tongtien = temp.Sum(x => x.SoLuong * x.SanPham.DonGia);
                                }
                                <li class="total-price">Tổng: <span style="font-size: 20px">@total đ</span></li>
                            </ul>
                            <input type="hidden" name="TTien" value="@tongtien" />
                            <div class="order-btn">
                                <button type="submit" class="site-btn place-btn">Đặt hàng</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

<footer class="footer-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="footer-left">
                    <div class="footer-logo">
                        <a href="@Url.Action("Index", "Home")"><img src="@Url.Content("~/assets/img/logo.jpg")" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1">
                <div class="footer-widget">
                    <h5>Thông tin</h5>
                    <ul>
                        <li><a href="@Url.Action("About", "Home")">Về Winxshop</a></li>
                        <li><a href="@Url.Action("Contact", "Home")">Liên hệ</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="newslatter-item">
                    <h5>Join Our Newsletter Now</h5>
                    <p>Get E-mail updates about our latest shop and special offers.</p>
                    <form action="#" class="subscribe-form">
                        <input type="text" placeholder="Enter Your Mail">
                        <button type="button">Subscribe</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-reserved">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright-text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                    <div class="payment-pic">
                        <img src="@Url.Content("~/assets/img/payment-method.png")" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

Team9_winxshop/Views/GioHangs/Create.cshtml
@model Team9_winxshop.Models.ChiTietGioHang

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ChiTietGioHang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaGH, "MaGH", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaGH", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaGH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, "MaSP", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaSP", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Team9_winxshop/Views/GioHangs/Details.cshtml
@model Team9_winxshop.Models.ChiTietGioHang

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ChiTietGioHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioHang.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioHang.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SanPham.MaLoaiSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPham.MaLoaiSP)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaCTGH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Team9_winxshop/Views/GioHangs/Index.cshtml
@model IEnumerable<Team9_winxshop.Models.ChiTietGioHang>
@using Team9_winxshop.Models

@{
    ViewBag.Title = "Index";
}

<!-- Header Section Begin -->
<header class="header-section">
    <div class="header-top">
        <div class="container">
            <div class="ht-left">
                <div class="mail-service">
                    <i class=" fa fa-envelope"></i>
                    winxshop@gmail.com
                </div>
                <div class="phone-service">
                    <i class=" fa fa-phone"></i>
                    +65 11.188.888
                </div>
            </div>
            <div class="ht-right">
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="login-panel">Đăng xuất</a>
                    }
                }
                else
                {
                    <a href="@Url.Action("Login", "Account")" class="login-panel"><i class="fa fa-user"></i>Đăng nhập</a>
                }
            </div>
        </div>
    </div>
    <div class="container">
        <div class="inner-header">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="logo">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="@Url.Content("~/assets/img/logo.jpg")" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-7 col-md-7">
                    <form action="@Url.Action("Search", "SanPhams")" method="get">
                        <div class="advanced-search" style="width: 500px;">
                            <div class="input-group">
                                <input type="text" maxlength="30" name="Keyword" placeholder="Nhập sản phẩm bạn muốn tìm kiếm">
                                <button type="submit" style="right: -200px;"><i class="ti-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-3 text-right col-md-3">
                    <ul class="nav-right">
                        <li class="cart-icon">
                            <a href="@Url.Action("Index", "GioHangs")">
                                <i class="icon_bag_alt"></i>
                                <span>@((Session["ShoppingCart"] as List<ChiTietGioHang>)?.Count.ToString()) </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="nav-item">
        <div class="container">
            <div class="nav-depart">
                <div class="depart-btn">
                    <i class="ti-menu"></i>
                    <span>All departments</span>
                    <form action="@Url.Action("Search", "SanPhams")" method="get">
                        <ul class="depart-hover">
                            <li><button type="submit" name="Keyword" value="NU" style="display: block; font-size: 16px; color: #e7ab3c; padding-left: 40px; padding-top: 16px; padding-right: 30px; border: none; background-color: #fff">Thời trang nữ</button></li>
                            <li><button type="submit" name="Keyword" value="NAM" style="display: block; font-size: 16px; color: #e7ab3c; padding-left: 40px; padding-top: 16px; padding-right: 30px; border: none; background-color: #fff">Thời trang nam</button></li>
                        </ul>
                    </form>
                </div>
            </div>
            <nav class="nav-menu mobile-menu">
                <ul>
                    <li class="active"><a href="@Url.Action("Index", "Home")">Trang chủ</a></li>
                    <li><a href="@Url.Action("Index2", "SanPhams")">Sản phẩm</a></li>
                    <li><a href="@Url.Action("About", "Home")">Về Winxshop</a></li>
                    <li><a href="@Url.Action("Contact", "Home")">Liên hệ</a></li>
                </ul>
            </nav>
            <div id="mobile-menu-wrap"></div>
        </div>
    </div>
</header>
<div class="breadcrumb-text product-more">
    <a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Trang chủ</a>
    <span>Giỏ hàng</span>
</div>
@if ((Session["ShoppingCart"] as List<ChiTietGioHang>).Count == 0)
{
    <div style="padding: 50px 0 50px 50px; font-size: 40px">Giỏ hàng của bạn đang trống</div>
    <div class="col-lg-4">
        <div class="cart-buttons">
            <a href="@Url.Action("Index2", "SanPhams")" class="primary-btn up-cart">Tiếp tục mua sắm</a>
        </div>
    </div>
}
else
{
    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <form action="@Url.Action("UpdateCart", "GioHangs")" method="get">
                        <div class="cart-table">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Hình ảnh</th>
                                        <th class="p-name">Sản phẩm</th>
                                        <th>Đơn giá</th>
                                        <th>Số lượng</th>
                                        <th>Thành tiền</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var product in Model)
                                    {
                                        <tr>
                                            <td class="cart-pic first-row">
                                                <a href="@Url.Action("Details", "SanPhams", new { id = product.SanPham.MaSP })">
                                                    <img src="@Url.Content(product.SanPham.HinhAnh)" alt="" width="120px" height="140px">
                                                </a>
                                            </td>
                                            <td class="cart-title first-row">
                                                <span style="font-size: 13px; color: #b2b2b2">@product.SanPham.MaSP</span>
                                                <a href="@Url.Action("Details", "SanPhams", new { id = product.SanPham.MaSP })">
                                                    <h5>@product.SanPham.TenSP</h5>
                                                </a>
                                                <span>Size: @product.SanPham.Size</span>
                                            </td>
                                            <td class="p-price first-row">@product.SanPham.DonGia.ToString("N0")đ</td>
                                            <td class="qua-col first-row">
                                           @if (product.SoLuong > product.SanPham.SoLuong)
                                            {
                                                <div class="quantity">
                                                    <input name="quantity" type="number" value="@product.SanPham.SoLuong" min="1" max="@product.SanPham.SoLuong" />
                                                </div>
                                                <td class="total-price first-row">@((product.SanPham.DonGia * product.SanPham.SoLuong).ToString("N0"))đ</td>
                                            }
                                            else
                                            {
                                                <div class="quantity">
                                                    <input name="quantity" type="number" value="@product.SoLuong" min="1" max="@product.SanPham.SoLuong" />
                                                </div>
                                                <td class="total-price first-row">@((product.SanPham.DonGia * product.SoLuong).ToString("N0"))đ</td>
                                            }
                                                </td>
                                                <td class="close-td first-row">@Html.ActionLink("Xóa", "Delete", "GioHangs", new { productId = product.SanPham.MaSP })</td>
                                            </tr>
                                        }
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="cart-buttons">
                                    <a href="@Url.Action("Index2", "SanPhams")" class="primary-btn continue-shop">Tiếp tục mua sắm</a>
                                    <input type="submit" value="Cập nhật giỏ hàng" class="primary-btn up-cart" style="position: absolute;" />
                                </div>
                            </div>
                            <div class="col-lg-4 offset-lg-4">
                                <div class="proceed-checkout">
                                    <ul>
                                        @{
                                            List<ChiTietGioHang> temp = (List<ChiTietGioHang>)Session["ShoppingCart"];
                                            var total = String.Format("{0:N0}", temp.Sum(x => x.SoLuong * x.SanPham.DonGia));
                                        }
                                        <li class="cart-total">Tổng tiền:<span>@total đ</span></li>
                                    </ul>
                                    <a href="@Url.Action("CheckOut", "GioHangs")" class="proceed-btn">THANH TOÁN</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
}


<footer class="footer-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="footer-left">
                    <div class="footer-logo">
                        <a href="@Url.Action("Index", "Home")"><img src="@Url.Content("~/assets/img/logo.jpg")" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1">
                <div class="footer-widget">
                    <h5>Thông tin</h5>
                    <ul>
                        <li><a href="@Url.Action("About", "Home")">Về Winxshop</a></li>
                        <li><a href="@Url.Action("Contact", "Home")">Liên hệ</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="newslatter-item">
                    <h5>Join Our Newsletter Now</h5>
                    <p>Get E-mail updates about our latest shop and special offers.</p>
                    <form action="#" class="subscribe-form">
                        <input type="text" placeholder="Enter Your Mail">
                        <button type="button">Subscribe</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-reserved">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright-text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                    <div class="payment-pic">
                        <img src="@Url.Content("~/assets/img/payment-method.png")" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>