Team9_winxshop/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team9_winxshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();
        }
    
        public string MaSP { get; set; }
        public string MaLoaiSP { get; set; }
        public string TenSP { get; set; }
        public string Size { get; set; }
        public int SoLuong { get; set; }
        public int DonGia { get; set; }
        public string Mau { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}

Team9_winxshop/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using Team9_winxshop.Models;

namespace Team9_winxshop.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SanPhamsController : Controller
    {
        private CT25Team19Entities db = new CT25Team19Entities();

        // GET: SanPhams
        public ActionResult Index()
        {
            var model = db.SanPhams.ToList();
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Search(string keyword)
        {
            if( keyword.Trim(' ') == "")
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                var model = db.SanPhams.ToList();
                model = model.Where(p => p.TenSP.ToLower().Contains(keyword.ToLower())
                                    || p.Mau.ToLower().Contains(keyword.ToLower())
                                    || p.MaLoaiSP.ToLower().Contains(keyword.ToLower())
                                    || p.LoaiSanPham.TenLoaiSP.ToLower().Contains(keyword.ToLower())).ToList();
                ViewBag.Keyword = keyword;
                return View("Index2", model);
            }
        }

        public ActionResult Search2(string keyword)
        {
            var model = db.SanPhams.ToList();
            model = model.Where(p => p.TenSP.ToLower().Contains(keyword.ToLower())
                                || p.MaSP.ToLower().Contains(keyword.ToLower())
                                || p.LoaiSanPham.TenLoaiSP.ToLower().Contains(keyword.ToLower())).ToList();
            ViewBag.Keyword = keyword;
            return View("Index", model);

        }

        [AllowAnonymous]
        // for Customer
        public ActionResult Index2()
        {
            var model = db.SanPhams.ToList();
            return View(model);
        }

        [AllowAnonymous]
        // GET: SanPhams/Details/5
        public ActionResult Details(string id)
        {
            var model = db.SanPhams.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams, "MaLoaiSP", "TenLoaiSP");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SanPham model)
        {
            ValidateProduct(model);
            if (ModelState.IsValid)
            {
                db.SanPhams.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        private void ValidateProduct(SanPham sanPham)
        {
            if(sanPham.DonGia < 0)
            {
                ModelState.AddModelError("DonGia", "Đơn giá phải lớn hơn 0");
            }
            if(sanPham.SoLuong < 0)
            {
                ModelState.AddModelError("SoLuong", "Số lượng phải lớn hơn 0");
            }
        }

        // GET: SanPhams/Edit/5
        public ActionResult Edit(string id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SanPham sanPham)
        {
            ValidateProduct(sanPham);
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // GET: SanPhams/Delete/5
        public ActionResult Delete(string id)
        {
            var model = db.SanPhams.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var model = db.SanPhams.Find(id);
            db.SanPhams.Remove(model);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Team9_winxshop/Views/SanPhams/Create.cshtml
@model Team9_winxshop.Models.SanPham

@{
    ViewBag.Title = "Create";
}

<header class="header-section">
    <div class="header-top">
        <div class="container">
            <div class="ht-left">
                <div class="mail-service">
                    <i class=" fa fa-envelope"></i>
                    winxshop@gmail.com
                </div>
                <div class="phone-service">
                    <i class=" fa fa-phone"></i>
                    +65 11.188.888
                </div>
            </div>
            <div class="ht-right">
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="login-panel">Log off</a>
                    }
                }
                else
                {
                    <a href="@Url.Action("Login", "Account")" class="login-panel"><i class="fa fa-user"></i>Login</a>
                }
            </div>
        </div>
    </div>
    <div class="container">
        <div class="inner-header">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="logo">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="@Url.Content("~/assets/img/logo.png")" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<h2>Thêm sản phẩm</h2>


@using (Html.BeginForm("Create", "SanPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="form-group col-md-6">
                <label class = "control-label col-md-3">Mã sản phẩm <span style="color: red">*</span></label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaSP, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger"})
                </div>
            </div>

            <div class="form-group col-md-6">
                <label class = "control-label col-md-4">Loại sản phẩm <span style="color: red">*</span></label>
                <div class="col-md-10" style="max-width: 66%">
                    @Html.DropDownList("MaLoaiSP", null, htmlAttributes: new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class = "control-label col-md-2">Tên sản phẩm <span style="color: red">*</span></label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class = "control-label col-md-2">Size <span style="color: red">*</span></label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class = "control-label col-md-2">Số lượng <span style="color: red">*</span></label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class = "control-label col-md-2">Đơn giá <span style="color: red">*</span></label>
            <div class="col-md-10">
                <div class="input-group">
                    @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control", @required = "required", min = 0 } })
                    <div class="input-group-append">
                        <span class="input-group-text">vnđ</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class = "control-label col-md-2">Màu <span style="color: red">*</span></label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mau, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Mau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class = "control-label col-md-2">Hình ảnh <span style="color: red">*</span></label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-4">
                <input type="submit" value="Create" class="btn btn-default" style="border-color: #e7ab3c;" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Team9_winxshop/Views/SanPhams/Index.cshtml
@model IEnumerable<Team9_winxshop.Models.SanPham>

@{
    ViewBag.Title = "Index";
}

<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Header Section Begin -->
<header class="header-section">
    <div class="header-top">
        <div class="container">
            <div class="ht-left">
                <div class="mail-service">
                    <i class=" fa fa-envelope"></i>
                    winxshop@gmail.com
                </div>
                <div class="phone-service">
                    <i class=" fa fa-phone"></i>
                    +65 11.188.888
                </div>
            </div>
            <div class="ht-right">
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="login-panel">Đăng xuất</a>
                    }
                }
                else
                {
                    <a href="@Url.Action("Login", "Account")" class="login-panel"><i class="fa fa-user"></i>Đăng nhập</a>
                }
            </div>
        </div>
    </div>
    <div class="container">
        <div class="inner-header">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="logo">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="@Url.Content("~/assets/img/logo.jpg")" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-7 col-md-7">
                    <form action="@Url.Action("Search2", "SanPhams")" method="get">
                        <div class="advanced-search" style="width: 500px;">
                            <div class="input-group">
                                <input type="text" maxlength="30" name="Keyword" placeholder="Nhập sản phẩm bạn muốn tìm kiếm">
                                <button type="submit" style="right: -200px;"><i class="ti-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="nav-item">
        <div class="container">
            <div class="nav-depart">
                <div class="depart-btn">
                    <i class="ti-menu"></i>
                    <span>All departments</span>
                    <form action="@Url.Action("Search", "SanPhams")" method="get">
                        <ul class="depart-hover">
                            <li><button type="submit" name="Keyword" value="Nữ" style="display: block; font-size: 16px; color: #e7ab3c; padding-left: 40px; padding-top: 16px; padding-right: 30px; border: none; background-color: #fff">Thời trang nữ</button></li>
                            <li><button type="submit" name="Keyword" value="Nam" style="display: block; font-size: 16px; color: #e7ab3c; padding-left: 40px; padding-top: 16px; padding-right: 30px; border: none; background-color: #fff">Thời trang nam</button></li>
                        </ul>
                    </form>
                </div>
            </div>
            <nav class="nav-menu mobile-menu">
                <ul>
                    <li><a href="@Url.Action("Index", "Home")">Trang chủ</a></li>
                    <li class="active"><a href="@Url.Action("Index2", "SanPhams")">Sản phẩm</a></li>
                    <li><a href="@Url.Action("About", "Home")">Về Winxshop</a></li>
                    <li><a href="@Url.Action("Contact", "Home")">Liên hệ</a></li>
                </ul>
            </nav>
            <div id="mobile-menu-wrap"></div>
        </div>
    </div>
</header>

<h2>Danh sách sản phẩm</h2>

<p>
    <a href="@Url.Action("Create")" style="">Thêm sản phẩm</a>
</p>
<table class="table">
    <tr>
        <th>
            Mã sản phẩm
        </th>
        <th>
            Tên sản phẩm
        </th>
        <th>
            Size
        </th>
        <th>
            Số lượng
        </th>
        <th>
            Đơn giá
        </th>
        <th>
            Màu
        </th>
        <th>
            Hình ảnh
        </th>
        <th>
            Loại sản phẩm
        </th>
        <th></th>
    </tr>

    @foreach (var product in Model)
    {
        <tr>
            <td>
                @product.MaSP
            </td>
            <td>
                @product.TenSP
            </td>
            <td>
                @product.Size
            </td>
            <td>
                @product.SoLuong
            </td>
            <td>
                @product.DonGia.ToString("N0")@("đ")
            </td>
            <td>
                @product.Mau
            </td>
            <td>
                <img src="@Url.Content(product.HinhAnh)" style="width: 70px; height: 80px" />
            </td>
            <td>
                @product.LoaiSanPham.TenLoaiSP
            </td>
            <td>
                <a href="@Url.Action("Edit", new { id = product.MaSP })">
                    <i class="fa fa-edit"></i>
                </a> |
                <a href="@Url.Action("Delete", new { id = product.MaSP })">
                    <i class="fa fa-trash"></i>
                </a>
            </td>
        </tr>
    }

</table>

Team9_winxshop/Views/SanPhams/Index2.cshtml
@model IEnumerable<Team9_winxshop.Models.SanPham>
@using Team9_winxshop.Models

@{
    ViewBag.Title = "Home Page";
}

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="header-top">
            <div class="container">
                <div class="ht-left">
                    <div class="mail-service">
                        <i class=" fa fa-envelope"></i>
                        winxshop@gmail.com
                    </div>
                    <div class="phone-service">
                        <i class=" fa fa-phone"></i>
                        +65 11.188.888
                    </div>
                </div>
                <div class="ht-right">
                    @if (Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:document.getElementById('logoutForm').submit()" class="login-panel">Đăng xuất</a>
                        }
                    }
                    else
                    {
                        <a href="@Url.Action("Login", "Account")" class="login-panel"><i class="fa fa-user"></i>Đăng nhập</a>
                    }
                </div>
            </div>
        </div>
        <div class="container">
            <div class="inner-header">
                <div class="row">
                    <div class="col-lg-2 col-md-2">
                        <div class="logo">
                            <a href="@Url.Action("Index", "Home")">
                                <img src="@Url.Content("~/assets/img/logo.jpg")" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-7">
                        <form action="@Url.Action("Search", "SanPhams")" method="get">
                            <div class="advanced-search" style="width: 500px;">
                                <div class="input-group">
                                    <input type="text" maxlength="30" name="Keyword" placeholder="Nhập sản phẩm bạn muốn tìm kiếm">
                                    <button type="submit" style="right: -200px;"><i class="ti-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-3 text-right col-md-3">
                        <ul class="nav-right">
                            <li class="cart-icon">
                                <a href="@Url.Action("Index", "GioHangs")">
                                    <i class="icon_bag_alt"></i>
                                    <span>@((Session["ShoppingCart"] as List<ChiTietGioHang>)?.Count.ToString()) </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="nav-item">
            <div class="container">
                <div class="nav-depart">
                    <div class="depart-btn">
                        <i class="ti-menu"></i>
                        <span>All departments</span>
                        <form action="@Url.Action("Search", "SanPhams")" method="get">
                            <ul class="depart-hover">
                                <li><button type="submit" name="Keyword" value="NU" style="display: block; font-size: 16px; color: #e7ab3c; padding-left: 40px; padding-top: 16px; padding-right: 30px; border: none; background-color: #fff">Thời trang nữ</button></li>
                                <li><button type="submit" name="Keyword" value="NAM" style="display: block; font-size: 16px; color: #e7ab3c; padding-left: 40px; padding-top: 16px; padding-right: 30px; border: none; background-color: #fff">Thời trang nam</button></li>
                            </ul>
                        </form>
                    </div>
                </div>
                <nav class="nav-menu mobile-menu">
                    <ul>
                        <li><a href="@Url.Action("Index", "Home")">Trang chủ</a></li>
                        <li class="active"><a href="@Url.Action("Index2", "SanPhams")">Sản phẩm</a></li>
                        <li><a href="@Url.Action("About", "Home")">Về Winxshop</a></li>
                        <li><a href="@Url.Action("Contact", "Home")">Liên hệ</a></li>
                    </ul>
                </nav>
                <div id="mobile-menu-wrap"></div>
            </div>
        </div>
    </header>
    <!-- Header End -->
    <div class="breacrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Trang chủ</a>
                        <span>Sản phẩm</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="product-shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-8 order-2 order-lg-1 produts-sidebar-filter">
                    <div class="filter-widget">
                        <h4 class="fw-title">Danh mục sản phẩm</h4>
                        <form action="@Url.Action("Search", "SanPhams")" method="get">
                            <ul class="filter-catagories">
                                <li><button type="submit" name="Keyword" value="Áo nam" style="display: block; font-size: 20px; color: #e7ab3c;border: none; background-color: #fff">Áo nam</button></li>
                                <li><button type="submit" name="Keyword" value="Áo nữ" style="display: block; font-size: 20px; color: #e7ab3c;border: none; background-color: #fff">Áo nữ</button></li>
                                <li><button type="submit" name="Keyword" value="Quần nam" style="display: block; font-size: 20px; color: #e7ab3c;border: none; background-color: #fff">Quần nam</button></li>
                                <li><button type="submit" name="Keyword" value="Quần nữ" style="display: block; font-size: 20px; color: #e7ab3c;border: none; background-color: #fff">Quần nữ</button></li>
                                <li><button type="submit" name="Keyword" value="Giầy nam" style="display: block; font-size: 20px; color: #e7ab3c;border: none; background-color: #fff">Giầy nam</button></li>
                                <li><button type="submit" name="Keyword" value="Giầy nữ" style="display: block; font-size: 20px; color: #e7ab3c;border: none; background-color: #fff">Giầy nữ</button></li>
                                <li><button type="submit" name="Keyword" value="Kính" style="display: block; font-size: 20px; color: #e7ab3c;border: none; background-color: #fff">Kính mát</button></li>
                                <li><button type="submit" name="Keyword" value="Nón" style="display: block; font-size: 20px; color: #e7ab3c;border: none; background-color: #fff">Nón</button></li>
                                <li><button type="submit" name="Keyword" value="Nhẫn" style="display: block; font-size: 20px; color: #e7ab3c;border: none; background-color: #fff">Nhẫn</button></li>
                                <li><button type="submit" name="Keyword" value="Đồng hồ" style="display: block; font-size: 20px; color: #e7ab3c;border: none; background-color: #fff">Đồng hồ</button></li>
                            </ul>
                        </form>
                    </div>
                </div>
                <div class="col-lg-9 order-1 order-lg-2">
                    <h3 style="color: #252525; padding-bottom: 15px; font-weight: 700;">Danh sách sản phẩm</h3>
                    <div class="product-list">
                        <div class="row">
                            @foreach (var product in Model)
                            {
                                <div class="col-lg-4 col-sm-6">
                                    <div class="product-item">
                                        <div class="pi-pic">
                                            <a href="@Url.Action("Details", new { id = product.MaSP })">
                                                <img src="@Url.Content(product.HinhAnh)" alt="">
                                            </a>
                                            <ul>
                                                <li class="quick-view" style="background-color: #e7ab3c;"><a href="@Url.Action("Details", "SanPhams",new { id = product.MaSP })" style="color: #ffffff">+ Quick View</a></li>
                                            </ul>
                                        </div>
                                        <div class="pi-text">
                                            <div class="catagory-name">@product.LoaiSanPham.TenLoaiSP</div>
                                            <a href="@Url.Action("Details", new { id = product.MaSP })">
                                                <h5>@product.TenSP</h5>
                                            </a>
                                            <div class="product-price">
                                                @product.DonGia.ToString("N0")@("đ")
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer-left">
                        <div class="footer-logo">
                            <a href="@Url.Action("Index", "Home")"><img src="@Url.Content("~/assets/img/logo.jpg")" alt=""></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 offset-lg-1">
                    <div class="footer-widget">
                        <h5>Information</h5>
                        <ul>
                            <li><a href="@Url.Action("About", "Home")">Về Winxshop</a></li>
                            <li><a href="@Url.Action("Contact", "Home")">Liên hệ</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="newslatter-item">
                        <h5>Join Our Newsletter Now</h5>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <form action="#" class="subscribe-form">
                            <input type="text" placeholder="Enter Your Mail">
                            <button type="button">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright-reserved">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="copyright-text">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </div>
                        <div class="payment-pic">
                            <img src="@Url.Content("~/assets/img/payment-method.png")" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
</body>